# Generated by Django 5.2.4 on 2026-01-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipaddress',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ipaddress',
            name='hostname',
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AlterField(
            model_name='ipaddress',
            name='status',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
